=== AlejoxVargas/practiceVersions/HTML-CSS/XML/Ejercicio1 XMLS PAISES/Paises.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="ciudades">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ciudad" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="pais">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="continente" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlejoxVargas/practiceVersions/HTML-CSS/XML/Ejercicio1 XMLS PAISES/Paises.xml
<?xml version="1.0" encoding="UTF-8"?>
<ciudades  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Paises.xsd" >
  <ciudad>
    <nombre>Nueva Delhi</nombre>
    <pais continente="asia">India</pais>
  </ciudad>
  <ciudad>
    <nombre>Lisboa</nombre>
    <pais continente="europa">Portugal</pais>
  </ciudad>
  <ciudad>
    <nombre>El Cairo</nombre>
    <pais continente="africa">Egipto</pais>
  </ciudad>
</ciudades>
