=== AlejoxVargas/practiceVersions/Examenes/Tercer Trimetre/DAM1_PR-Final_LM_230601_Alejandro_Vargas/DAM1_PR-Final_LM_230601_Alejandro_Vargas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="libreria">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="categoria">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Ficción"/>
                    <xs:enumeration value="No Ficción"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="autor" type="xs:string" minOccurs="0"/>
              <xs:element name="precio">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="euros" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="dolares" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="cantidad" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:decimal">
                        <xs:maxInclusive value="100"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="año" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:integer">
                  <xs:minInclusive value="1500"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlejoxVargas/practiceVersions/Examenes/Tercer Trimetre/DAM1_PR-Final_LM_230601_Alejandro_Vargas/DAM1_PR-Final_LM_230601_Alejandro_Vargas.xml
<?xml version="1.0" encoding="UTF-8"?>
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DAM1_PR-Final_LM_230601_Alejandro_Vargas.xsd">
  <libro año="2018">
    <categoria>Ficción</categoria>
    <titulo>Libro de Ficcion 1</titulo>
    <autor>Autor 1</autor>
    <precio cantidad="30.14">
      <euros/>
    </precio>
  </libro>
  <libro año="2078">
    <categoria>Ficción</categoria>
    <titulo>Libro de Ficcion 2</titulo>
    <autor>Autor 2</autor>
    <precio cantidad="12.80">
      <euros/>
    </precio>
  </libro>
  <libro año="1845">
    <categoria>No Ficción</categoria>
    <titulo>Libro de No Ficcion 1</titulo>
    <autor>Autor 3</autor>
    <precio cantidad="92.00">
      <dolares/>
    </precio>
  </libro>
  <libro año="1998">
    <categoria>No Ficción</categoria>
    <titulo>Libro de No Ficcion 2</titulo>
    <precio cantidad="82.68">
      <dolares/>
    </precio>
  </libro>
</libreria>
