=== AlejoxVargas/practiceVersions/HTML-CSS/XML/XLM COPY EDITOR/Receta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Cantidad">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="unidad" type="xs:string" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Descripcion" type="xs:string"/>
  <xs:element name="Ingrediente">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Cantidad"/>
        <xs:element ref="Item"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Ingredientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Ingrediente" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Instrucciones">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Paso" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Item" type="xs:string"/>
  <xs:element name="Nombre" type="xs:string"/>
  <xs:element name="Paso" type="xs:string"/>
  <xs:element name="Receta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Nombre"/>
        <xs:element ref="Descripcion"/>
        <xs:element ref="Ingredientes"/>
        <xs:element ref="Instrucciones"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlejoxVargas/practiceVersions/HTML-CSS/XML/XLM COPY EDITOR/Receta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Receta.css" type="text/css"?>
<!--DOCTYPE  Receta SYSTEM "Receta.xsd"-->
<Receta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Receta.xsd">
  <Nombre>Tortilla de patatas</Nombre>
  <Descripcion>
        La tradicional y típica tortilla de patatas, 
        tal como la hacen todas las madres. 
    </Descripcion>
  <Ingredientes>
    <Ingrediente>
      <Cantidad unidad="pieza">3</Cantidad>
      <Item>Patata</Item>
    </Ingrediente>
    <Ingrediente>
      <Cantidad unidad="pieza">4</Cantidad>
      <Item>Huevos</Item>
    </Ingrediente>
    <Ingrediente>
      <Cantidad unidad="litro">0.1</Cantidad>
      <Item>Aceite</Item>
    </Ingrediente>
  </Ingredientes>
  <Instrucciones>
    <Paso>
            Pelar y cortar la patata en rodajas 
        </Paso>
    <Paso>
            Poner aceite en una paella 
        </Paso>
    <!-- Y asi seguimos... -->
  </Instrucciones>
</Receta>
